@startchen
' --- DIAGRAM SCALING & COMPRESSION SECRETS ---
left to right direction
skinparam nodesep 10
skinparam ranksep 10
scale max 1000 width
scale max 1000 height

entity blood_group {
    id
    group
}

entity system_user {
    id
    user
    pwd
    name
    role
}

entity donor {
    id
    fname
    lname
    dob
    sex
    phone
    bg_id
}

entity inventory {
    id
    units
    exp
}

entity hospital {
    id
    name
    lic
    type
    phone
}

entity donation {
    id
    type
    date
    units
}

entity request {
    id
    pat
    diag
    type
    units
    urg
}

entity fulfill {
    id
    units
    temp
}

entity appointment {
    id
    date
    time
    status
}

relationship Uses_Portal {
}

relationship Collects_Blood {
}

relationship Approves_Release {
}

relationship Has_Blood_Type {
}

relationship Stocked_As {
}

relationship Collected_As {
}

relationship Requested_As {
}

relationship Donates_Blood {
}

relationship Sets_Appointment {
}

relationship Raises_Request {
}

relationship Is_Fulfilled_By {
}

relationship Supplies_Blood {
}

system_user -1- Uses_Portal
Uses_Portal -1- donor
system_user -1- Uses_Portal
Uses_Portal -1- hospital

system_user -1- Collects_Blood
Collects_Blood -N- donation

system_user -1- Approves_Release
Approves_Release -N- fulfill

blood_group -1- Has_Blood_Type
Has_Blood_Type -N- donor

blood_group -1- Stocked_As
Stocked_As -N- inventory

blood_group -1- Collected_As
Collected_As -N- donation

blood_group -1- Requested_As
Requested_As -N- request

donor -1- Donates_Blood
Donates_Blood -N- donation

donor -1- Sets_Appointment
Sets_Appointment -N- appointment

hospital -1- Raises_Request
Raises_Request -N- request

request -1- Is_Fulfilled_By
Is_Fulfilled_By -N- fulfill

inventory -1- Supplies_Blood
Supplies_Blood -N- fulfill

@endchen


